DEBUG: False
DATA: 'E:/tyw-data/original/rename-txt'
PROCESSOR:
  USE_CLEAR: False  # 因为使用了缓存，已经缓存了清洗后的文件
  DISCARD: 300000
PPG:
  ORIGIN_DISCARD: 10000  # 原始数据首尾丢弃长度
  LOOK_BACK: 200
  THRESHOLD: 200
  INTERVAL_UP_THRESHOLD: 3000
EDA:
  FEATS_MEAN: False
  FEATS_MAX_MIN: True
  MAX_MIN: 0.
  L_TH: 0.8
  H_TH: 1.2
  FEATS_LEARN: False
  ADAPT_TH: False

TRAIN:
  HUNGRY_MODEL:
    TYPE: 'lstm'
    COLUMN_NUM: 1
    LOOK_BACK: 200
    LAYERS: [1, 30, 20, 2]
    EPOCHS: 32

CACHE:
  CLEAR: 'E:/tyw-data/original/clear'
  PPG: 'E:/tyw-data/cache/ppg'

DRAW:
  PATH: 'E:/tyw-data/draw'
  PPG: False
  PPG_PATH: 'E:/tyw-data/draw/ppg'
  EDA_WHOLE: True

TEST:
  HUNGRY_MODEL:
    OPEN: False
    PATH: 'G:/Python3.7/tyw/tyw/model_file/200-30-20-0.869565_cont.h5'
  FEAR_MODEL:
    OPEN: True