DEBUG: False
DATA: 'E:/tyw-data/original/rename-txt'
PROCESSOR:
  USE_CLEAR: False
  DISCARD: 300000
PPG:
  LOOK_BACK: 200
  THRESHOLD: 200
  INTERVAL_UP_THRESHOLD: 3000
EDA:
  FEATS_MEAN: False
  FEATS_MAX_MIN: True
  MAX_MIN: 0.
  L_TH: 0.8
  H_TH: 1.2
  FEATS_LEARN: False
  ADAPT_TH: False

TRAIN:
  HUNGRY_MODEL:
    TYPE: 'lstm'
    COLUMN_NUM: 1
    LOOK_BACK: 200
    LAYERS: [1, 30, 20, 2]
    EPOCHS: 32

CACHE:
  CLEAR: 'E:/tyw-data/original/clear'
  PPG: 'E:/tyw-data/cache/ppg'

DRAW:
  PPG: False
  PPG_PATH: 'E:/tyw-data/draw/ppg'

TEST:
  HUNGRY_MODEL:
    OPEN: False
    PATH: 'E:/体域网项目/codes/tyw/tyw/model_file/200-30-20-0.869565_cont.h5'
  FEAR_MODEL:
    OPEN: True