DEBUG: False
DATA_SRC: 'E:/tyw-data/original/rename-txt'
ANN_SRC: 'E:/tyw-data/original/anns'
CLEAR_SRC: 'E:/tyw-data/original/clear'
PROCESSOR:
  USE_CLEAR: False
  DISCARD: 300000
DRAW:
  EDA_WHOLE: False
  EDA_FEATURES: False
  EDA_FILES_MEAN: False
  EDA_FRAGMENTS: False
LOOK_BACK: 200
SAVE_CSV: False
PPG:
  CACHE: 'E:/tyw-data/cache/ppg'
  LOOK_BACK: 200
  THRESHOLD: 200
  INTERVAL_UP_THRESHOLD: 3000
EDA:
  FEATS_MEAN: False
  FEATS_MAX_MIN: True
  MAX_MIN: 0.
  L_TH: 0.8
  H_TH: 1.2
  FEATS_LEARN: False
  ADAPT_TH: False

TRAIN:
  HUNGRY_MODEL:
    TYPE: 'lstm'
    COLUMN_NUM: 1
    LAYERS: [1, 30, 20, 2]
    EPOCHS: 32