# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(740, 10, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(713, 0, 20, 711))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(760, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(850, 110, 133, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(760, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(850, 170, 133, 26))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(760, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(850, 230, 133, 26))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(760, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(850, 290, 133, 26))
        self.lineEdit_8.setObjectName("lineEdit_8")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 80, 661, 531))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.ecg_groupBox = QtWidgets.QGroupBox(self.widget)
        self.ecg_groupBox.setObjectName("ecg_groupBox")
        self.verticalLayout.addWidget(self.ecg_groupBox)

        self.ppg_groupBox = QtWidgets.QGroupBox(self.widget)
        self.ppg_groupBox.setObjectName("ppg_groupBox")
        self.verticalLayout.addWidget(self.ppg_groupBox)
        self.eda_groupBox = QtWidgets.QGroupBox(self.widget)
        self.eda_groupBox.setObjectName("eda_groupBox")
        self.verticalLayout.addWidget(self.eda_groupBox)
        self.skt_groupBox = QtWidgets.QGroupBox(self.widget)
        self.skt_groupBox.setObjectName("skt_groupBox")
        self.verticalLayout.addWidget(self.skt_groupBox)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 630, 661, 24))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_3.addWidget(self.checkBox_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_4.addWidget(self.checkBox_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.lineEdit_2.raise_()
        self.lineEdit_5.raise_()
        self.checkBox_4.raise_()
        self.lineEdit_4.raise_()
        self.label_4.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.checkBox.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.line.raise_()
        self.label_10.raise_()
        self.label_6.raise_()
        self.lineEdit_3.raise_()
        self.ecg_groupBox.raise_()
        self.label_11.raise_()
        self.lineEdit_6.raise_()
        self.label_12.raise_()
        self.lineEdit_7.raise_()
        self.label_13.raise_()
        self.lineEdit_8.raise_()
        self.ppg_groupBox.raise_()
        self.eda_groupBox.raise_()
        self.skt_groupBox.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "识别结果"))
        self.label_10.setText(_translate("MainWindow", "健康程度"))
        self.label_6.setText(_translate("MainWindow", "输入信号"))
        self.lineEdit_3.setText(_translate("MainWindow", "健康"))
        self.label_11.setText(_translate("MainWindow", "疲劳程度"))
        self.lineEdit_6.setText(_translate("MainWindow", "轻度疲劳"))
        self.label_12.setText(_translate("MainWindow", "饥饿程度"))
        self.lineEdit_7.setText(_translate("MainWindow", "不饿"))
        self.label_13.setText(_translate("MainWindow", "恐惧程度"))
        self.lineEdit_8.setText(_translate("MainWindow", "不恐惧"))
        self.ecg_groupBox.setTitle(_translate("MainWindow", "ECG信号波形"))
        self.ppg_groupBox.setTitle(_translate("MainWindow", "PPG信号波形"))
        self.eda_groupBox.setTitle(_translate("MainWindow", "EDA信号波形"))
        self.skt_groupBox.setTitle(_translate("MainWindow", "SKT信号波形"))
        self.checkBox.setText(_translate("MainWindow", "心率"))
        self.lineEdit.setText(_translate("MainWindow", "75"))
        self.label.setText(_translate("MainWindow", "次/分"))
        self.checkBox_2.setText(_translate("MainWindow", "体温"))
        self.lineEdit_2.setText(_translate("MainWindow", "36.4"))
        self.label_2.setText(_translate("MainWindow", "摄氏度"))
        self.checkBox_4.setText(_translate("MainWindow", "血糖"))
        self.lineEdit_4.setText(_translate("MainWindow", "5.2"))
        self.label_3.setText(_translate("MainWindow", "mmol/L"))
        self.checkBox_3.setText(_translate("MainWindow", "血氧饱和度"))
        self.lineEdit_5.setText(_translate("MainWindow", "99"))
        self.label_4.setText(_translate("MainWindow", "%"))
