# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(70, 30, 91, 28))
        self.comboBox.setObjectName("comboBox")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 32, 22))
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(21, 177, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(200, 30, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit_2.setGeometry(QtCore.QRect(380, 180, 81, 21))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(100, 180, 181, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 30, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(300, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_46 = QtWidgets.QLabel(self.groupBox)
        self.label_46.setGeometry(QtCore.QRect(20, 230, 171, 22))
        self.label_46.setObjectName("label_46")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 80, 441, 71))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_8.raise_()
        self.label_4.raise_()
        self.comboBox.raise_()
        self.label_12.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_5.raise_()
        self.label_13.raise_()
        self.lineEdit_7.raise_()
        self.label_15.raise_()
        self.label_10.raise_()
        self.lineEdit_4.raise_()
        self.label_9.raise_()
        self.lineEdit_3.raise_()
        self.label_10.raise_()
        self.lineEdit_4.raise_()
        self.label_9.raise_()
        self.lineEdit_3.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.timeEdit_2.raise_()
        self.progressBar.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.label_46.raise_()
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 30, 91, 28))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 40, 32, 22))
        self.label_14.setObjectName("label_14")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(21, 177, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 30, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.groupBox_2)
        self.timeEdit_3.setGeometry(QtCore.QRect(380, 180, 81, 21))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_2.setGeometry(QtCore.QRect(100, 180, 181, 21))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 30, 81, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(300, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 441, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 0, 5, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_2.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 2, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_2.addWidget(self.lineEdit_18, 1, 3, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_2.addWidget(self.lineEdit_19, 1, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 4, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_2.addWidget(self.lineEdit_20, 1, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(20, 230, 171, 22))
        self.label_47.setObjectName("label_47")
        self.comboBox_3.raise_()
        self.label_3.raise_()
        self.pushButton_3.raise_()
        self.timeEdit_3.raise_()
        self.progressBar_2.raise_()
        self.pushButton_4.raise_()
        self.label_5.raise_()
        self.layoutWidget.raise_()
        self.label_14.raise_()
        self.label_47.raise_()
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(70, 30, 91, 28))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(20, 40, 32, 22))
        self.label_29.setObjectName("label_29")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(21, 177, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 30, 81, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit_4.setGeometry(QtCore.QRect(380, 180, 81, 21))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar_3.setGeometry(QtCore.QRect(100, 180, 181, 21))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 30, 81, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(300, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 80, 441, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_3.addWidget(self.lineEdit_21, 0, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 0, 4, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_3.addWidget(self.lineEdit_22, 0, 5, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_3.addWidget(self.lineEdit_23, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 1, 2, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_3.addWidget(self.lineEdit_24, 1, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_3.addWidget(self.lineEdit_25, 1, 5, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 1, 4, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_3.addWidget(self.lineEdit_26, 1, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_3)
        self.label_48.setGeometry(QtCore.QRect(20, 230, 171, 22))
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_5.setGeometry(QtCore.QRect(70, 30, 91, 28))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(20, 40, 32, 22))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(21, 177, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setGeometry(QtCore.QRect(200, 30, 81, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.groupBox_4)
        self.timeEdit_5.setGeometry(QtCore.QRect(380, 180, 81, 21))
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.progressBar_4 = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar_4.setGeometry(QtCore.QRect(100, 180, 181, 21))
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName("progressBar_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(290, 30, 81, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(300, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 80, 441, 71))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_4.addWidget(self.lineEdit_27, 0, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 0, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 0, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 0, 4, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_4.addWidget(self.lineEdit_28, 0, 5, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_4.addWidget(self.lineEdit_29, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 1, 2, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_4.addWidget(self.lineEdit_30, 1, 3, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_4.addWidget(self.lineEdit_31, 1, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 1, 4, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_4.addWidget(self.lineEdit_32, 1, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_4)
        self.label_49.setGeometry(QtCore.QRect(20, 230, 171, 22))
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "饥饿训练"))
        self.label_12.setText(_translate("MainWindow", "模型"))
        self.label.setText(_translate("MainWindow", "训练进度"))
        self.pushButton.setText(_translate("MainWindow", "开始训练"))
        self.pushButton_2.setText(_translate("MainWindow", "取消训练"))
        self.label_2.setText(_translate("MainWindow", "训练时间"))
        self.label_46.setText(_translate("MainWindow", "验证集精度：90.1%"))
        self.label_4.setText(_translate("MainWindow", "参数1"))
        self.label_15.setText(_translate("MainWindow", "参数2"))
        self.label_9.setText(_translate("MainWindow", "参数3"))
        self.label_8.setText(_translate("MainWindow", "参数4"))
        self.label_13.setText(_translate("MainWindow", "参数5"))
        self.label_10.setText(_translate("MainWindow", "参数6"))
        self.groupBox_2.setTitle(_translate("MainWindow", "疲劳训练"))
        self.label_14.setText(_translate("MainWindow", "模型"))
        self.label_3.setText(_translate("MainWindow", "训练进度"))
        self.pushButton_3.setText(_translate("MainWindow", "开始训练"))
        self.pushButton_4.setText(_translate("MainWindow", "取消训练"))
        self.label_5.setText(_translate("MainWindow", "训练时间"))
        self.label_6.setText(_translate("MainWindow", "参数1"))
        self.label_25.setText(_translate("MainWindow", "参数2"))
        self.label_11.setText(_translate("MainWindow", "参数3"))
        self.label_26.setText(_translate("MainWindow", "参数4"))
        self.label_27.setText(_translate("MainWindow", "参数5"))
        self.label_28.setText(_translate("MainWindow", "参数6"))
        self.label_47.setText(_translate("MainWindow", "验证集精度：90.1%"))
        self.groupBox_3.setTitle(_translate("MainWindow", "恐惧训练"))
        self.label_29.setText(_translate("MainWindow", "模型"))
        self.label_7.setText(_translate("MainWindow", "训练进度"))
        self.pushButton_5.setText(_translate("MainWindow", "开始训练"))
        self.pushButton_6.setText(_translate("MainWindow", "取消训练"))
        self.label_30.setText(_translate("MainWindow", "训练时间"))
        self.label_31.setText(_translate("MainWindow", "参数1"))
        self.label_32.setText(_translate("MainWindow", "参数2"))
        self.label_33.setText(_translate("MainWindow", "参数3"))
        self.label_34.setText(_translate("MainWindow", "参数4"))
        self.label_35.setText(_translate("MainWindow", "参数5"))
        self.label_36.setText(_translate("MainWindow", "参数6"))
        self.label_48.setText(_translate("MainWindow", "验证集精度：90.1%"))
        self.groupBox_4.setTitle(_translate("MainWindow", "健康训练"))
        self.label_37.setText(_translate("MainWindow", "模型"))
        self.label_38.setText(_translate("MainWindow", "训练进度"))
        self.pushButton_7.setText(_translate("MainWindow", "开始训练"))
        self.pushButton_8.setText(_translate("MainWindow", "取消训练"))
        self.label_39.setText(_translate("MainWindow", "训练时间"))
        self.label_40.setText(_translate("MainWindow", "参数1"))
        self.label_41.setText(_translate("MainWindow", "参数2"))
        self.label_42.setText(_translate("MainWindow", "参数3"))
        self.label_43.setText(_translate("MainWindow", "参数4"))
        self.label_44.setText(_translate("MainWindow", "参数5"))
        self.label_45.setText(_translate("MainWindow", "参数6"))
        self.label_49.setText(_translate("MainWindow", "验证集精度：90.1%"))
